/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 micro.gltf --transform 
Files: micro.gltf [115.9KB] > C:\Users\Trey\Desktop\Hayley\hayley-website\public\micro-transformed.glb [763.38KB] (-559%)
Author: Ricardo Dias Teixeira (https://sketchfab.com/RicardoDiasTeixeira)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/microscope-swift-sw380b-f81d863bec684b00a9b1ba4c2d844001
Title: Microscope SWIFT SW380B
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const meshRef = useRef(null)
  useFrame(() => {
    if (meshRef.current) {
      meshRef.current.rotation.z += 0.01
    }
  })
  const { nodes, materials } = useGLTF('/micro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh ref={meshRef} geometry={nodes.MicroscopeBase_LowPoly__0.geometry} material={materials['Scene_-_Root']} position={[0, -15, 0]} rotation={[-2, 0.25, -250]} />
    </group>
  )
}

useGLTF.preload('/micro-transformed.glb')
